%% findall(X, phrase(grammar_ComplextArraySample,X,[]),AS),forall((member(N,AS)), writeln(N)).

%% Automatically generated by EDJ BPEL2DCG Transformer : Fri Nov 30 15:02:57 CET 2018

grammar_ComplextArraySample --> ["v0"], c_main, ["v"].

c_main --> ["receiveInput"], ["Assign"], ["replyOutput"].

