         
%% findall(X, phrase(grammar_HandleRequest,X,[]),AS),forall((member(N,AS)), writeln(N)).

%% Automatically generated by EDJ BPEL2DCG Transformer : Sun Dec 02 14:38:07 CET 2018

grammar_HandleRequest --> ["v0"], c_main, ["v"].

c_onm_handleRequest --> ["handleRequest"], ["PrepareHandleRequest"].
c_onm_handleComplexRequest --> ["handleComplexRequest"], ["PrepareHandleComplexRequest"].
c_onm_rejectRequest --> ["rejectRequest"], ["PrepareRejectRequest"].
c_onm_reinjectRequest --> ["reinjectRequest"], ["PrepareReinjectRequest"].
c_pick_HandleService --> ["HandleService"], c_onm_handleRequest.
c_pick_HandleService --> ["HandleService"], c_onm_handleComplexRequest.
c_pick_HandleService --> ["HandleService"], c_onm_rejectRequest.
c_pick_HandleService --> ["HandleService"], c_onm_reinjectRequest.
c_if_IfValid --> ["else"], ["PrepareRejectReq"], ["RejectRequestWS"].
c_if_IfValid --> ["IfValid"], ["PrepareProcessRequest"], ["ProcessRequestWS"].
c_if_IfStandardRequest --> ["else"], ["PrepareCreateManualTask"], ["CreateManualTaskWS"].
c_if_IfStandardRequest --> ["IfStandardRequest"], ["PrepareCheckProcessability"], ["CheckProcessabilityWS"], ["AssignValid"], c_if_IfValid.
c_if_NotReinjectHandleRequest --> ["NotReinjectHandleRequest"], ["PrepareHandleRequestReply"], ["HandleRequestReply"], !.

c_if_NotReinjectHandleRequest --> [].
c_if_IfValidComplex --> ["else"], ["PrepareRejectReq"], ["RejectRequestWS"].
c_if_IfValidComplex --> ["IfValidComplex"], ["PrepareProcessRequest"], ["ProcessRequestWS"].
c_if_NotReinjectHandleComplexRequest --> ["NotReinjectHandleComplexRequest"], ["PrepareHandleComplexRequestReply"], ["HandleComplexRequestReply"], !.

c_if_NotReinjectHandleComplexRequest --> [].
c_if_HandleService --> ["elseif"], ["PrepareCheckProcessability"], ["CheckProcessabilityWS"], ["AssignValid"], c_if_IfValidComplex, c_if_NotReinjectHandleComplexRequest.
c_if_NotReinjectRejectRequest --> ["NotReinjectRejectRequest"], ["PrepareRejectRequestReply"], ["RejectRequestReply"], !.

c_if_NotReinjectRejectRequest --> [].
c_if_HandleService --> ["elseif"], ["PrepareInvokeRejectRequest"], ["InvokeRejectRequestWS"], c_if_NotReinjectRejectRequest.
c_if_HandleService --> ["else"], ["UnknownRequest"].
c_if_HandleService --> ["HandleService"], ["PrepareClassifyRequest"], ["ClassifyRequestWS"], ["AssignRequestType"], c_if_IfStandardRequest, c_if_NotReinjectHandleRequest.
c_if_IfReinject --> ["IfReinject"], ["PrepareReinjectRequestReply"], ["ReinjectRequestReply"], !.

c_if_IfReinject --> [].
c_main --> c_pick_HandleService, c_if_HandleService, c_if_IfReinject.

start1:-
open('d:/request.txt',write,Stream),
findall(X, phrase(grammar_HandleRequest,X,[]),AS),
forall((member(N,AS)), (writeln(Stream,N))),
close(Stream).
