%% findall(X, phrase(grammar_InvokeIncrementProcess,X,[]),AS),forall((member(N,AS)), writeln(N)).

%% Automatically generated by EDJ BPEL2DCG Transformer : Fri Nov 30 15:05:36 CET 2018

grammar_InvokeIncrementProcess --> ["v0"], c_main, ["v"].

c_main --> ["receiveInput"], ["PrepareInvokeIncrement"], ["Invoke"], ["PrepareOutput"], ["replyOutput"].
