%% findall(X, phrase(grammar_WhileSample,X,[]),AS),forall((member(N,AS)), writeln(N)).

%% Automatically generated by EDJ BPEL2DCG Transformer : Fri Nov 30 15:02:05 CET 2018

grammar_WhileSample --> ["v0"], c_main, ["v"].

c_Whilex_block --> ["LoopAssign"].
c_Whilex_block_seq --> c_Whilex_block.
c_Whilex_block_seq --> c_Whilex_block, c_Whilex_block.
c_Whilex_block_seq --> [].
c_while_Whilex --> ["Whilex"], c_Whilex_block_seq.
c_main --> ["receiveInput"], ["Assign"], c_while_Whilex, ["AssignOutput"], ["replyOutput"].